---
- name: Install prerequisites
  apt: pkg={{ item }} state=latest
  update_cache: yes
  with_items:
    - git
    - libav-tools
    - cmake
    - subversion
    - dh-autoreconf
    - libcurl4-openssl-dev
    - libssl-dev

- name: Get recent version of Raspberry Pi userland tools
  git: repo=https://github.com/raspberrypi/userland dest=/root/userland force=yes

- file: path=/root/userland/build state=directory

- name: Build Raspberry Pi userland tools
  shell: "{{ item }}"
  args:
    chdir: /root/userland/build
    creates: /opt/vc/lib/libmmal.so
  with_items:
    - cmake ..
    - make -
    - make install

- name: Get kerberos.io machinery source
  git:
    repo: https://github.com/kerberos-io/machinery
    dest: /root/kerberosio-machinery
    force: yes
#    version: v2.5.1

- file: path=/root/kerberosio-machinery/build state=directory

- name: Build kerberos.io machinery
  shell: "{{ item }}"
  args:
    chdir: /root/kerberosio-machinery/build
    creates: /usr/bin/kerberosio
  with_items:
    - cmake ..
    - make -j4
    - make -j4 check
    - make install

- name: Update kerberosio config
  lineinfile: dest=/etc/opt/kerberosio/config/config.xml regexp="<name type=\"text\">" line="<name type=\"text\">{{ inventory_hostname }}</name>"

- name: Update kerberosio config
  lineinfile: dest=/etc/opt/kerberosio/config/config.xml regexp="<timezone type=\"timezone\">" line="<timezone type=\"timezone\">Pacific-Auckland</timezone>"

- name: Update kerberosio cloud config
  template: src=cloud.xml.j2 dest=/etc/opt/kerberosio/config/cloud.xml

- name: Enable systemd
  service: name=kerberosio enabled=yes state=started

- cron:
    name: Clear out old capture files
    minute: 5
    hour: 4
    job: find /etc/opt/kerberosio/capture/ -mtime +4 -exec rm {} \;

- name: Disable Camera LED
  lineinfile: dest=/boot/config.txt regexp='^disable_camera_led$' line='disable_camera_led=1'
