---
# airplay playbook: define all the roles for airplay hosts

- hosts: airplay_servers
  remote_user: pi
  become_user: root
  become: yes

  roles:
    - airplay

  handlers:
    - include: handlers/handlers.yml
