---
- hosts: kerberosio_machinery_servers
  remote_user: pi
  become_user: root
  become: yes

  roles:
    - kerberosio_machinery
    - kerberosio_web

  handlers:
    - include: handlers/handlers.yml