---
- name: Set some /boot/config.txt parameters
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^gpu_mem=256', line: 'gpu_mem=256' }
    - { regexp: '^disable_camera_led=1', line: 'disable_camera_led=1' }
  notify: reboot

- name: Create stream systemd
  template: src=stream.service.j2 dest=/etc/systemd/system/stream.service

- name: Create start_stream.sh
  template: src=start_stream.sh.j2 dest=/usr/local/bin/start_stream.sh

- name: Make start_stream.sh executable
  file: path=/usr/local/bin/start_stream.sh mode=0755

- name: Enable & start stream systemd
  service: name=stream enabled=yes state=restarted

- name: Add bcm2835-v4l2 to /etc/modules
  lineinfile: dest=/etc/modules regexp='^bcm2835-v4l2' line='bcm2835-v4l2' state=present
  notify: reboot
