---
- name: Create mount point
  file: path=/mnt/external state=directory mode=0755

- name: Add mount to fstab
  lineinfile: dest=/etc/fstab regexp="{{ usb_disk_uuid }}" line="UUID={{ usb_disk_uuid }} /mnt/external ext4 defaults 0 2"

- name: Create seafile systemd
  template: src=seafile.service.j2 dest=/etc/systemd/system/seafile.service

- name: Create seahub systemd
  template: src=seahub.service.j2 dest=/etc/systemd/system/seahub.service

- name: Enable & start seafile systemd
  service: name=seafile enabled=yes state=started

- name: Enable & start seahub systemd
  service: name=seahub enabled=yes state=started

