---
- name: set hostname
  hostname: name={{ inventory_hostname }}

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"

- name: Copy timezone file
  template: src=timezone dest=/etc/timezone mode=0644
  register: timezone_result

- name: Set timezone
  command: dpkg-reconfigure -f noninteractive tzdata
  when: timezone_result.changed

- name: Some shell aliases for the user
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.bashrc line="{{ item }}"
  with_items:
  - "alias ls='ls -lhG'"

- name: Disable logging to /dev/xconsole   # By default nobody reads from /dev/xconsole and thus it overflows causing "action 'action 17' suspended" errors to syslog
  replace:
    dest=/etc/rsyslog.conf
    regexp='^daemon.*mail(.|\n)*?/dev/xconsole'
    replace='# Removed by Ansible'

- name: Enable SPI
  lineinfile: dest=/boot/config.txt regexp='^#(dtparam=spi=on)$' line='\1' backrefs=yes
  notify: reboot

- name: Use tmpfs for tmp folder
  lineinfile: dest=/etc/fstab line='tmpfs           /tmp              tmpfs   defaults,noatime,mode=1777 0       0'

- name: Use tmpfs for log folder
  lineinfile: dest=/etc/fstab line='tmpfs           /var/log          tmpfs   defaults,noatime,mode=0755 0       0'

- name: Use tmpfs for lock folder
  lineinfile: dest=/etc/fstab line='tmpfs           /var/lock         tmpfs   defaults,noatime,mode=0755 0       0'

- include: user.yml
