---
- apt: pkg=samba state=latest

- name: Add Samba config
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf

- name: Configure Samba users.
  shell: >
    (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd -s -a {{ item.username }}
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"
  with_items: "{{ samba_users }}"
  loop_control:
    label: "{{ item.username }}"

- file:
    state: directory
    path: /nas

- lineinfile:
    dest: /etc/fstab
    line: 'UUID=1262e745-4095-4db0-ac0d-0abce7852255	/nas	ext3	nosuid,nodev,nofail,x-gvfs-show	0	0'

- shell: mount -a

- name: Enable services
  service:
      name: "{{ item }}"
      enabled: yes
      state: started
  with_items:
    - smbd.service
    - avahi-daemon.service
