---
- name: Set some /boot/config.txt parameters
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^gpu_mem=256', line: 'gpu_mem=256' }
    - { regexp: '^disable_camera_led=1', line: 'disable_camera_led=1' }
  notify: reboot

- name: Install gstreamer
  apt: pkg={{ item }} state=latest
  with_items:
    - gstreamer1.0-tools

- name: Install prerequisites
  apt: pkg={{ item }} state=latest
  with_items:
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev

- name: Get gst-rpicamsrc source
  git: repo=git://github.com/thaytan/gst-rpicamsrc.git dest=/root/gst-rpicamsrc force=yes

- name: Build gst-rpicamsrc
  shell: "{{ item }}"
  args:
    chdir: /root/gst-rpicamsrc
    creates: /usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstrpicamsrc.la
  with_items:
    - ./autogen.sh --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf/
    - make
    - sudo make install

- name: Create stream systemd
  template: src=stream.service.j2 dest=/etc/systemd/system/stream.service

- name: Enable & start stream systemd
  service: name=stream enabled=yes state=restarted


